#!/bin/bash

while true
do
    pingoutput=
    echo
    while [[ "$pingoutput" != "OK" ]]
    do
    	echo -n .
    	pingoutput=$(/usr/bin/python ping.py /dev/ttyUSB1 9600)
    done
    echo
    echo Programming...
    espeak "X B Programming"

    make firmware profileXB3 verify

    if [ $? -eq 0 ]
    then espeak "X B Complete"
    else espeak "X B Failed"
    fi

done