#!/bin/bash

while true
do
	make read > /dev/null 2> /dev/null
	while [ $? -ne 0 ]
	do
		echo -n .
		make read > /dev/null 2> /dev/null
	done

	echo -e "\n\033[1;33mProgramming\033[0m\n"
	espeak "Programming"
	make fuse firmware HEX=hex/mrbw-cst_v1.2.2_4ec009.hex

	if [ $? -eq 0 ]
	then 
		echo -e "\033[0;32mComplete\033[0m\n"
		espeak "Complete"
	else 
		echo -e "\033[0;31mFailed\033[0m\n"
		espeak "Failed"
	fi
	
	# Loop until it fails (disconnected)
	make read > /dev/null 2> /dev/null
	while [ $? -eq 0 ]
	do
		echo -n +
		make read > /dev/null 2> /dev/null
	done

	sleep 1
done
